---
- name: Homebrew casks - Install
  homebrew_cask:
    name:
      - 1password
      - 1password-cli
      - asana
      - aws-vault
      - chromedriver
      - claude
      - cleanshot
      - firefox
      - ghostty
      - github
      - google-chrome
      - monitorcontrol
      - notion
      - orbstack
      - raycast
      - rectangle
      - signal
      - sketch
      - slack
      - spotify
      - transmission
      - transmit
      - whatsapp
    state: installed
  ignore_errors: true
