---
- name: Homebrew casks - Install
  homebrew_cask:
    name: "{{ item }}"
    state: installed
  ignore_errors: true
  loop:
  - 1password
  - 1password-cli
  - asana
  - aws-vault
  - chromedriver
  - claude
  - cleanshot
  - firefox
  - ghostty
  - github
  - google-chrome
  - monitorcontrol
  - notion
  - raycast
  - rectangle
  - signal
  - sketch
  - slack
  - spotify
  - transmission
  - transmit
  - whatsapp
